config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :videos do
    resources :comments
  end
  root 'categories#index'

  get '/api/:id', to: 'videos#video_json'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :videos, dependent: :destroy
    validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :video

  validates :author, presence: true
  validates :content, presence: true
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :category
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :url, presence: true
  validates :category_id, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    before_action :find_category, only: [:show, :edit, :update, :destroy]


    def index
        @categories = Category.all
        @videos = Video.all
        
        return @categories, @videos
    end

    def new
        @category = Category.new
    end
    
    def create
        @category = Category.new(category_params)
        if @category.save()
            redirect_to root_path
        else 
            render 'new'
        end
    end
    
    def show
        @videos = Video.where(category_id: params[:id])
        return @category, @videos 
    end
    
    def edit
    end

    def update
        if @category.update(category_params)
            redirect_to category_path
        else 
            redirect_to 'edit'
        end
    end

    def destroy
        @category.destroy
        redirect_to root_path
    end


    private
        
        def category_params
            params.require(:category).permit(:name, :is_favorite)
        end

        def find_category
            @category = Category.find(params[:id])
        end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :find_video, only: [:create, :edit, :update, :destroy]
	before_action :find_comment, only: [:edit, :update, :destroy]

    def create
        @video = Video.find(params[:video_id])
        @comment = @video.comments.create(comment_params)

        if @comment.video
            redirect_to video_path(@video)
        else
            render 'new'
        end
    end

    def edit
	end

	def update
		if @comment.update(comment_params)
			redirect_to video_path(@video)
		else
			render 'edit'
		end
	end

	def destroy
		@comment.destroy
		redirect_to video_path(@video)
	end


    private
        def comment_params
            params.require(:comment).permit(:author, :content)
        end

        def find_video
			@video = Video.find(params[:video_id])
		end

		def find_comment
			@comment = @video.comments.find(params[:id])
		end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    
    before_action :find_video, only: [:show, :edit, :update, :destroy]
    before_action :find_category, only: [:new, :edit]
    before_action :find_video_by_category, only: [:video_json]
    
    def new
        @video = Video.new
        unless @categories.any?
            render 'erro'
        end
    end
    
    def create
        @video = Video.new(video_params)
        @video.category_id = params[:category_id]
        if @video.save()
            redirect_to root_path
        else 
            render 'new'
        end
    end
    
    def show
        @category_id = @video.category_id
        @category = Category.find(@category_id).name   
    end
    
    def edit
    end

    def update
        if @video.update(video_params)
            redirect_to video_path
        else 
            redirect_to 'edit'
        end
    end

    def destroy
        @video.destroy
        redirect_to root_path
    end

    def video_json
        if @video.any?
            @category = Category.find(params[:id]).name
            render json: {status: 200, category: @category  ,video: @video.as_json(only: [:url, :title])}
        else
            render json: {status: 404,
                message: "Não há videos cadastrados ou categoria inexistente"
            }
        end
    end



    private
        
        def video_params
            params.require(:video).permit(:url, :title, :category_id)
        end

        def find_video
            @video = Video.find(params[:id])
        end

        def find_category
            @categories = Category.all.map{ |c| [c.name, c.id] }
        end

        def find_video_by_category
            @video = Video.where(category_id: params[:id])
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
    def url_to_id(url)
        id_video = url.split('=').last
        video_url = "https://www.youtube.com/embed/#{id_video}?autoplay=1"
    end
end

app/views/categories/_anyCategory.html.erb
<div class="alert alert-danger" role="alert">
     Não há categorias cadastradas
</div>
<%= link_to "Criar Categoria", new_category_path, class: "btn btn-primary" %>

app/views/categories/_form.html.erb
<%= simple_form_for @category do |c| %>
    <div class="form-group">

        <%= c.input :name, label: "Nome da Categoria ", input_html: {class: "form-control"}%>
    </div>
    <div class="form-group"> 
        <%= c.input :is_favorite,label: "Favorita", as: :boolean, boolean_style: :inline %>
    </div>
        <%= c.button :submit, value: "Criar Categoria", class: "btn btn-success" %>
    </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editar Categoria</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="container">
    <% if @categories.any? %>
    <div class = 'container'>
    <div class="row">
        <% @categories.each do |category| %>
            <div class='col-md-3 category'>
            <h2>
                <%=category.name%>
            </h2>
            <% if category.is_favorite?  %>
                <% @videos.each do |video| %>
                    <% if category.id == video.category_id %>
                        <ul class="list-group">
                            <li class ="list-group-item"><%= link_to "#{video.title}", video_path(video)%></li>
                        </ul>
                    <%end%>
            <%end%>
        <% end %>
            <%= link_to "Ver Categoria", category_path(category), class: "btn btn-info"%>
            <%= link_to "Adicionar Video", new_video_path, class: "btn btn-primary" %>
        </div>
    <% end %>
    </div>
    <%else%>
        <%= render 'anyCategory' %>
    <% end %>
    </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Video</th>
      <th scope="col">Editar</th>
      <th scope="col">Excluir</th>
    </tr>
  </thead>
  <tbody>
    <% @videos.each do |video| %>
        <tr>
            <td><%= link_to "#{video.title}", video_path(video) %></td>
            <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_video_path(video) %></td>
            <td><%= link_to '<i class="fa fa-trash"></i>'.html_safe, video_path(video), method: :delete, data: {confirm: "Você tem certeza?"}%></td>
        </tr>
    <%end%>
  </tbody>
</table>

<%= link_to "Editar Categoria", edit_category_path(@category), class: "btn btn-warning" %>
<%= link_to "Excluir Categoria", category_path(@category), method: :delete, data: {confirm: "Você tem certeza?"}, class: "btn btn-danger"%>

app/views/comments/_comment.html.erb
<div class="comment">

    <p class="comment-content"><%= comment.content %></p>
    <div class="container-comment">
        <p class= "comment-posted">Posted by <%= comment.author %> <%= time_ago_in_words(comment.created_at) %> ago</p>
            <%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_video_comment_path(comment.video, comment) %>
            <%= link_to '<i class="fa fa-trash"></i>'.html_safe, video_comment_path(comment.video, comment), method: :delete, data: {confirm: "Você tem certeza?"}%>
    </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@video, @video.comments.build]) do |c| %>
	<div class="form-group">
		<%= c.input :author, label: "Autor ", input_html: {class: "form-control"} %>
	</div>
	<div class="form-group">
    	<%= c.input :content, label: "Comentario ", input_html: {class: "form-control"}%>
	</div>
	<%= c.button :submit, class: "btn btn-success", value: "Comentar" %>
	</div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editar Comentario: </h1>

<%= simple_form_for([@video, @comment]) do |c| %>
	<div class="form-group">
		<%= c.input :author, label: "Autor ", input_html: {class: "form-control"} %>
	</div>
	<div class="form-group">
    	<%= c.input :content, label: "Comentario ", input_html: {class: "form-control"}%>
	</div>
	<%= c.button :submit, class: "btn btn-success", value: "Comentar" %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoFacil</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  	<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-header">
				<%= link_to "Video Fácil", root_path, class: "navbar-brand" %>
			</div>
			<div class="navbar-nav">
				<p><%= link_to "Criar Categoria", new_category_path, class: "navbar-text" %></p>
      </div>
      <div class="navbar-nav">
			  <p><%= link_to "Adicionar Video", new_video_path, class: "navbar-text" %></p>
      </div>  
		</div> 
	</div>
	</nav>
  <p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
  <body>
    <%= yield %>
  </body>
</html>

app/views/videos/_form.html.erb
<%= simple_form_for @video  do |v| %>
	<div class = "form-group">
		<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Selecionar Categoria") %>
	</div>
	<div class="form-group">
		<%= v.input :title, label: "Titulo do Video", input_html: {class: "form-control"} %>
	</div>
	<div class="form-group">
		<%= v.input :url, input_html: {class: "form-control"} %>
	</div>
	<%= v.button :submit, class: "btn btn-primary" %>
	</div>
<% end %>

app/views/videos/edit.html.erb
<h1>Edit Video</h1>

<%= render 'form' %>

app/views/videos/erro.html.erb
<div class="alert alert-danger" role="alert">
  Não há categorias cadastradas
</div>

<%= link_to "Criar Categoria", new_category_path, class: "btn btn-primary" %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form' %>

app/views/videos/show.html.erb
<div class="video-show">
    <h2><%= @video.title %></h2>

    <div class="embed-responsive embed-responsive-16by9">
        <iframe  src= "<%= url_to_id @video.url %>" ></iframe>
    </div>

    <div class="row">
    <div class="col-md-6">
        <h1>Comentarios: </h1>
        <%= render @video.comments %>
    </div>
    <div class="col-md-6">
        <h4> Deixe seu comentario: </h4>
        <%= render 'comments/form'%>
    </div>
</div>